version: '3.7'
services:
  web:
    build:
      context: ./nginx
    ports:
      - 8000:80
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
